/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** JavaScript Import specifier structure. */
export interface JsImport {
  /** Module specifier (if safe string) */
  n?: string
  /** Import type */
  t: number
  /** Module specifier start position (UTF-16 code units) */
  s: number
  /** Module specifier end position (UTF-16 code units) */
  e: number
  /** Statement start position (UTF-16 code units) */
  ss: number
  /** Statement end position (UTF-16 code units) */
  se: number
  /** Dynamic import position (UTF-16 code units) */
  d: number
  /** Attributes index (UTF-16 code units) */
  a: number
  /** Import attributes as array of [key, value] pairs */
  at: Array<Array<string>> | null
}
/** JavaScript Export specifier structure. */
export interface JsExport {
  /** Export name */
  n: string
  /** Local name */
  ln?: string
  /** Export name start position (UTF-16 code units) */
  s: number
  /** Export name end position (UTF-16 code units) */
  e: number
  /** Local name start position (UTF-16 code units) */
  ls: number
  /** Local name end position (UTF-16 code units) */
  le: number
}
/** JavaScript parse result structure. */
export interface JsParseResult {
  imports: Array<JsImport>
  exports: Array<JsExport>
  facade: boolean
  hasModuleSyntax: boolean
}
/**
 * Parse JavaScript source code to extract imports and exports.
 *
 * # Arguments
 *
 * * `source` - The JavaScript source code to parse
 * * `_name` - Optional file name (for error messages, currently unused)
 *
 * # Returns
 *
 * A `JsParseResult` containing:
 * - `imports`: Array of import specifiers
 * - `exports`: Array of export specifiers
 * - `facade`: Whether this is a facade module (pure imports/exports)
 * - `has_module_syntax`: Whether the file contains any module syntax
 *
 * # Errors
 *
 * Returns an error if the source code contains syntax errors.
 */
export declare function parse(source: string, name?: string | undefined | null): JsParseResult
